jobs:

# Shell script infrastructure deployment to AWS
  - name: tf_Deploy
    type: runSh
    steps:
      - IN: integration_aws
      - IN: repo_tfScripts
      - IN: params_tfScripts
      - IN: trigger_tf_deploy
      - TASK:
        - script: . /build/IN/repo-tfScripts/gitRepo/provInfra.sh
